### ISSUE TITLE
Error installing EasyAdminBundle Cannot load resource "@EasyAdminBundle/Controller/". 

### ISSUE THREAD

**Issue by im-timbo** [npotier/EasyAdminBundle#1]
Hi, i'm installing this bundle but i get a error, the error is:
Cannot load resource "@EasyAdminBundle/Controller/". Make sure the "EasyAdminBundle/Controller/" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@EasyAdminBundle/Controller/" is not empty.
I'm trying to install this bundle without composer because my internt have proxy, and i can't install this bundle with composer, all settings work great but routing not. What i can do for solve this?.

**Comment by npotier** [comment]
Hi, This repo is not maintained, I invite you to check the official repo https://github.com/javiereguiluz/EasyAdminBundle

**Comment by im-timbo** [comment]
OK man, thanks a lot.
