### ISSUE TITLE
HTML not interpreted after installation

### ISSUE THREAD

**Issue by g21designz** [npotier/EasyAdminBundle#2]
Hi, 
I've just install and configure EASYADMINBUNDLE, 
and when i go to the admin part of my website i got non interpreted HTML code (see attached file)
![capture](https://cloud.githubusercontent.com/assets/25388285/22420619/94c2a262-e6e3-11e6-8c02-e05c9ab2ef16.PNG)

Someone got the same problem?

Thanks for your help

**Comment by npotier** [comment]
Ho @g21designz I think you should use the official Repo : https://github.com/javiereguiluz/EasyAdminBundle

**Comment by g21designz** [comment]
ok thanks
